---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.app }}
    version: {{ .Values.appVersion}}
    commitId: {{ .Values.commitId}}
    gitBranch: {{ .Values.gitBranch }}
    gitRepoName: {{ .Values.gitRepoName}}
    gitOrgName: {{ .Values.gitOrgName}}
    appdAppName: {{ .Values.appdAppName }}
    framework: {{ .Values.framework }}
spec:
  replicas: {{ .Values.replicas.count }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        version: {{ .Values.appVersion}}
        commitId: {{ .Values.commitId}}
        gitBranch: {{ .Values.gitBranch }}
        gitRepoName: {{ .Values.gitRepoName}}
        gitOrgName: {{ .Values.gitOrgName}}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - {{ .Values.nodeAffinity }}
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.artifactoryUrl }}/{{ .Values.dockerRepository }}/{{ .Values.serviceName }}:{{ .Values.imageTag }}"
        ports:
        - containerPort: {{ .Values.port | default 8080}}
          name: port
          protocol: TCP
        resources:
          requests:
            memory: {{.Values.replicas.memory | default "128Mi"}}
            cpu: {{ .Values.replicas.cpu | default "50m"}}
          limits:
            memory: {{ .Values.replicas.memory | default "256Mi" }}
            cpu: {{ .Values.replicas.cpu | default "100m"}}
        envFrom:
        {{- if and .Values.config .Values.config.production }}
        - configMapRef:
            name: {{ .Values.app }}
        {{end}}
        {{- if and .Values.secrets .Values.secrets.production }}
        - secretRef:
            name: {{ .Values.app }}
        {{end}}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}