---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ .Values.app }}
    version: {{ .Values.appVersion}}
    commitId: {{ .Values.commitId}}
    gitBranch: {{ .Values.gitBranch }}
    gitRepoName: {{ .Values.gitRepoName}}
    gitOrgName: {{ .Values.gitOrgName}}
    release: prometheus
    team: team-foundation
  name: {{ .Values.app }}
spec:
  endpoints:
  - path: /metrics
    port: service-port
    interval: 30s
  selector:
    matchLabels:
      app: {{ .Values.app }}